### ISSUE TITLE
Hello, would you merge pull request 6? 

### ISSUE THREAD

**Issue by edwinyzh** [ying32/htmlparser#7]
Here: https://github.com/ying32/htmlparser/pull/6

Thanks.

**Comment by ying32** [comment]
看样子是合并了，感谢。 现在自己因为没有使用过了，所以基本也就没维护了。

**Comment by edwinyzh** [comment]
谢谢！我后续的修改都会给这发PR。

**Comment by ying32** [comment]
好的，感谢
